[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
shader-macro = { path = "../shader-macro"}
ash = "0.38.0"
ash-window = "0.13.0"
bytemuck = { version = "1.25.0", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["debug", "deref"] }
gltf = "1.4.1"
hashbrown = "0.17.1"
itertools = "0.14.0"
nalgebra = { version = "0.35.0", features = ["bytemuck"] }
nalgebra-glm = "0.21.0"
shipyard = "0.11.3"
tracing = "0.1.44"
tracy-client = { version = "0.19.0", default-features = false }
vk-mem = "0.5.0"
winit = "0.30.13"
rapier3d = "0.34.0"
dear-imgui-rs = { version = "0.18.0",  git = "https://github.com/Qustio/dear-imgui-rs", branch = "ash-render-features"}
dear-imgui-ash = { version = "0.18.0", features = ["dynamic-rendering", "render-pass"], git = "https://github.com/Qustio/dear-imgui-rs", branch = "ash-render-features" }
dear-imgui-winit = { version = "0.18.0", features = ["native-platform-support"], git = "https://github.com/Qustio/dear-imgui-rs", branch = "ash-render-features" }

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.30.13", features = ["android-native-activity"] }
android-activity = { version = "0.6", features = ["native-activity"]}


[features]
tracy = ["tracy-client/enable"]
gpu_label = []
